#!/usr/bin/perl
use strict; use warnings;
use lib '/home/hqin/lib/perl'; 
use Util;

my $debug = 1;

#my $coatfl = "_simple.coat.orth.pairs.122007.csv";
my $coatfl = "_test.csv";
my $root = "/home/hqin/coat.protein07/orthog.analysis/phylo/";

open (IN, "<$coatfl");
my $count = 0;
while (my $line = <IN>) {
  chomp $line; 
  my ( $bg, @ids) = split ( /\t/, $line );

  chdir $bg; 
  if ($debug) {    system( "pwd" );  }

  ### generate paup file
  open (IN, "<cds.nexus"); my @lines = <IN>; close (IN);

  open (OUT, ">cds-mb.nexus"); 
  foreach my $line (@lines) { 
    if ( $line =~ "datatype=protein" ) {
	$line =~ s/protein/dna/o;
    } 
    if ( $line =~ "symbols=\"ATCG\"" ) {
	$line =~ s/symbols=\"ATCG\"//o;
    }
    print OUT $line; 
  }

  my $mblines = "
 begin mrbayes;

	[ MrBayes block generated by GUMP at Auburn University (http://gump.auburn.edu/srsantos/mrbayes_form/) on Friday, December 21st 2007
	Script originally written by Roderic Page (r.page\@bio.gla.ac.uk)]

	[ Set the parameters of the likelihood model ]
	lset 
		nst=6
		rates=gamma
 		nucmodel=codon;

	set autoclose=yes;

	[ Set Markov chain Monte Carlo parameters ]
	mcmcp
		ngen=50000
		printfreq=100
		samplefreq=100
		nchains=1
		savebrlens=yes
		filename=mbresults;

	[ Go! ]
	mcmc;

	[ Summarise the results ]
	sumt 
		filename=mbresults
		burnin=100
		contype=allcompat;
	Sumt
end; ";
  print OUT "$mblines";

  close (OUT);
 
 # system( "paup cds-paup.nexus" );
  system( "mb cds-mb.nexus" );

  $count ++;   print "**** count = $count \n\n";
  chdir $root;

 # if( ( $debug ) & ( $count > 2 ) ) { exit; }  
}
close (IN);

exit;


