((Bha, Bcl),(Bpu,(Bli,(Bam,(Bmo,Bsu)))),(Bwe #1,(Bce #1,(Ban #1,Bth #1)#1)#1)#1); 
 ((Bha,Bcl), (Bpu,(Bli,(Bam,Bsu ))),  (Bwe #1,(Bce #1,(Ban #1,Bth #1)#1)#1)#1);
 ((Bha,Bcl), (Bpu,(Bli,Bsu)),  (Bwe #1,(Bce #1,(Ban #1,Bth #1)#1)#1)#1);
(Bha, (Bpu,(Bli,(Bam,(Bmo,Bsu)))),  (Bwe #1,(Bce #1,(Ban #1,Bth #1)#1)#1)#1);
((Bli,(Bmo,Bsu)),  (Bwe #1,(Bce #1,(Ban #1,Bth #1)#1)#1)#1);
 ((Bpu,(Bli,(Bam,(Bmo,Bsu)))),  (Bwe #1,(Bce #1,(Ban #1,Bth #1)#1)#1)#1);
 ( Bha, (Bli,(Bmo,Bsu)),  (Bwe #1,(Bce #1,(Ban #1,Bth #1)#1)#1)#1);
 (Bcl, (Bpu,(Bli,(Bam, Bsu), Bce #1)));
 (   (Bam,     Bsu ) ,  (Bwe #1,(Bce #1,(Ban #1,Bth #1)#1)#1)#1);
 ((Bha,Bcl),       (Bli,(Bam,(Bmo,Bsu))),  (Bwe #1,(Bce #1,(Ban #1,Bth #1)#1)#1)#1);
((Bha,Bcl), (Bpu,(Bli,(Bam,(Bmo,Bsu))))                         );
(Bha, (Bpu,(Bli,(Bam,(Bmo,Bsu)))) );
(Bpu,(Bli,(Bmo,Bsu)));
 ((Bha,Bcl), (Bpu,(Bli,(Bam,(Bmo,Bsu)))),  Bce #1);
( Bha,       (Bpu,     (Bam,Bsu)));
 (    Bli,(Bam,Bsu),  (Bwe #1,(Bce #1,(Ban #1,Bth #1)#1)#1)#1);
(Bpu, Bam, (Bmo, Bsu));
 ( Bha, (Bpu, (Bam,(Bmo,Bsu))),  (Ban #1,Bth #1)#1);
(Bsu, (Ban, Bwe), Bha);
 (( Bcl,  (Bli,(Bam, Bsu ))),  (Bwe #1,(Bce #1,(Ban #1,Bth #1)#1)#1)#1);
 ((Bha,Bcl),(Bpu,(Bam,Bsu )),  (Bwe #1,(Bce #1,(Ban #1,Bth #1)#1)#1)#1);
 ( (Bli,(Bam,(Bmo,Bsu))),  (Bwe #1,(Bce #1,(Ban #1,Bth #1)#1)#1)#1);
 ((Bli, (Bsu, Bmo)),   ((Ban #1, Bth #1),Bce #1, Bwe #1)#1);
 (Bcl, (Bpu,(Bli,(Bam,     Bsu ))),  (Bwe #1,(Bce #1,(Ban #1,Bth #1)#1)#1)#1);
 ((Bpu,(Bli,(Bam,Bsu))),  (Bce #1,(Ban #1,Bth #1)#1)#1);
(Bpu, Bli,(Bam,Bsu));
